# This is a basic workflow to help you get started with Actions

name: Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4

    - name: setup python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script # run main.py
      run: python main.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: EnigTech2-Unofficial-Dev
        # A file, directory or wildcard pattern that describes what to upload
        path: build/output
